name: flutter_my_books
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0  
  design_system: 
      path: ../design_system  
  image_picker: ^1.0.7
  http: ^1.1.0
  flutter_bloc: ^8.1.5
  uno: ^1.1.9
  flutter_dotenv: ^5.1.0
  jwt_decode: ^0.3.1
  shared_preferences: ^2.2.2
  image: ^4.2.0
  image_cropper: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/images/png/book.png
    - assets/images/png/adicionar-imagem.png

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
